### ISSUE TITLE
Add documentation about contributing & a changelog

### ISSUE THREAD

**Issue by friedow** [bptlab/chimera#122]
To better onboard new developers it would be very helpful, to have a CONTRIBUTING documentation for the project as proposed by GitHub (https://help.github.com/articles/setting-guidelines-for-repository-contributors/). 
It should describe
- the code of conduct
- the expected format for issues and pull requests
- the vision of the project 

It should point new contributors to the relevant resources in the wiki, e.g. how to set up the IDE for debugging, troubleshooting common issues, and so on.

Furthermore, the project should include a CHANGELOG following the suggestions of [keepachangelog](https://keepachangelog.com/en/1.0.0/).

**Comment by tommartensen** [comment]
@marhew Maybe as a suggestion, when you are already adding a contribution manifest, Github actually proposes to have several document besides a `README`, `LICENSE` and a `CONTRIBUTION`. You can see them [here (section 3)](https://opensource.guide/starting-a-project/), e.g. a `CODE OF CONDUCT`, `ISSUE TEMPLATE` and `PULL REQUEST TEMPLATE`. These are super helpful to onboard new developers or to report bugs from your users! I guess the project would also benefit from a [`CHANGELOG` document](https://keepachangelog.com/en/1.0.0/). 

I have seen the effort to document some things in the wiki, but to be honest, I did not have a closer look, because it was too much unstructured information. Maybe as you are the modeling experts, you can come up with some nice way to show the CI process for example (if you need any ideas in regards to CI/CD and testing, deployment, scaling, bit of security validation and how to such automate things, feel free to reach out, as I was able to get some experience in that area through my job).

**Comment by marhew** [comment]
I think the hard part is the information architecture for the wiki, i.e. how the information is structured to be easily findable. For example, there is a wiki page, describing how to setup up debugging in your IDE (https://github.com/bptlab/chimera/wiki/IdeaTomcat), but even I had to look for it. 
I will have a look into the sources you pointed out and improve the structure of our wiki.
