### ISSUE TITLE
Support for concurrent fragment instances

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#57]
The fragment-based Case Management approach Chimera has the intention that different instances of the same fragment can run concurrently, e.g. as a case worker I want to be able to work on reviewing several papers (or have a colleague review another paper at the same time). The formalization states that **a new fragment instance for a fragment is created, when the previous instance of that fragment becomes active, i.e. when an activity instance begins.** 

When a fragment instance becomes `active` depends on the type of the first control node after the start event:
- [x] If the first control node is an automatic task, it would be started automatically, thus spawning infinitely many new fragment instances. **This is undesired!** To prevent it, automatic task that are the first control node of a fragment should not be started automatically.
- [x] If the first control node is a gateway, the fragment instance should not be considered active if the gateway opens and enables (some of) its successors. Rather, when one of the succeeding control node begins, should the fragment instance be activated.
- [x] If the first control node is a message receive event, the **fragment instance becomes active after the events occurs**, i.e. after a notification from Unicorn is received. 
- [x] If the first control node is a message send event, the **sending of the message needs to be triggered manually by the user.**
- [x] The first control node **may not be a timer event**. The case model parser should reject such models. However, we should consider to allow modeling timer start events in the future.
- [x] Restrict the maximum amount of FragmentInstances a Case can hold so the concurrency does not lead to an overflow

**Acceptance criteria**:
- Create a test case model in which several instances of the same fragment can run concurrently
- Test whether multiple instances of the fragment exist
- Test whether fewer than infinite instances are created
- Check whether the test satisfies the points to consider mentioned above 

**Tests needed**:
- [x] Test with TimerEvent as first ControlNode -> decline
- [x] Test with SendEvent as first ControlNode
- [x] Test with MessageReceiveEvent as first ControlNode
- [x] Test with Activity as first ControlNode
- [x] Test with infinite creation of Fragment Instances

**Comment by janwestphal306** [comment]
The starting of concurrent fragment instances should be different for the event instances and their behavior.
 - Timer Events should not trigger the start of a new fragment instance because this could lead to an overflow of fragment instances
 - Start Events & End Events should not trigger it because of the same reason
 - Send Events are processed immediatly so to prevent an overflow they should not trigger a new fragment instance either. If the user wants to trigger events easy he needs to put an activity behind it or do it the present way and instantiate a new case

**Comment by janwestphal306** [comment]
I want to propose some ideas for the concurrent running fragment instances because there are many ways to handle it. In addition, the problem goes hand in hand how to handle fragment preconditions.
Therefore, handling the first occurring control node depending of its type is key.

**Current State**:
Activities trigger a new fragment instance if they are begun. Predefined automatic tasks, like the webservice task, will not be executed automatically and has to be begun manually.
Catch events trigger a new fragment instance when they begun and register at Unicorn.
Throw events and timer events should not trigger the instantiation of a fragment because that could lead to an overflow a fragment instances. I am still not sure whether catch events could lead to that behavior, too.

**Possible Solutions**:
- Throw events and timer events can simply not trigger a new fragment instantiation. Instead only activities and catch events that are in the control flow behind these events should be able to trigger the fragment instantiation. This means that fragments with just one throw event or timer event as the only control node (except start and end event) will not trigger a new instantiation of the fragment. This could be accepted or fragment that have this appearance could be forbidden by the parser. Reasons for the latter could be, that fragments normally have at least one activity. However, it is a restriction that needs to be known by user because there might be case models that want to use exactly this behavior. 

- Events could be handled like automatic tasks. Means that under some circumstances they need to be begun manually, e.g. as first control node or if they are more than one condition set in the control node precondition. This would solve two problems at one. However, this does not solve the problem for timer events because timer events without an automatic beginning lose their use. They could be handled like in the solution above.

**Comment by marhew** [comment]
Updated the description of this issue to include the decision for event instances.

As much as I like the proposal to wait for the activity instance after an event instance, this would interfere with fragment pre-conditions, because a fragment instance could do stuff, e.g. send a message, and then become disabled again.
