### ISSUE TITLE
deal with changed database schemas

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#93]
Since using EclipseLink as persistence layer the database schema is automatically generated based on the @Entity annotations in the class files. Adding new fields to classes causes a change in the database schema. Right now, this causes a lot of SQL exceptions when running the system and is only solved by manually dropping and re-creating the database.

**We need a better way to handle this situation!** Either
- let EclipseLink drop and re-create the schema automatically
- find a way to migrate the schema

**Comment by Tobias314** [comment]
EclipseLink does not provide tools to migrate the schema I would say.
See: https://stackoverflow.com/questions/2052781/support-for-schema-migrations-with-jpa

**Comment by Tobias314** [comment]
As EclipseLink does not provide a simple way to drop and recreate the schema only when it's necessary, I suggest the following for development:

- Keep the EclipseLink ddl generation option `create-or-extend-tables` for "normal" development, whenever there are no changes which are incompatible with the current database schema.

- Deploy once with the `drop-and-create-tables` option set whenever you made a change so that the new schema is not compatible with the old schema (for example when you introduce a new attribute which isn't allowed to be null or when you change a primary key). Change the option back to `create-or-extend-tables` when you finish your schema changes and have deployed the application ( using `drop-and-create-tables` all the time during development would be possible as well but it takes a lot of time to recreate the database after every little change and is also very inconvenient because you would have to redeploy all your CaseModels)

To change between `create-or-extend-tables` and `drop-and-create-tables` go in the persistence.xml and change the value of the property with the name `eclipselink.ddl-generation`.

**Comment by marhew** [comment]
Thanks for the research @Tobias314. 
Could we make the ddl generation option a Maven variable. Then we would need a way to check whether the database needs to be re-created. Previously, Chimera used a variable in the pom.xml that was compared to a version table in the database. If the variable in the pom.xml was higher the schema would be automatically recreated. Can you think of a similar way to realize an automatic schema recreation by setting the ddl option?

**Comment by marhew** [comment]
@Tobias314 Please document what you just told me :-)

**Comment by Tobias314** [comment]
See https://github.com/bptlab/chimera/wiki/Database-Schema-Versions
